GET localhost:8080/v1/user/6/
###
GET localhost:8080/v1/tool/1/
###
GET localhost:8080/v1/client/1/
###
GET localhost:8080/v1/blank/2/

###
GET localhost:8080/v1/users
###
GET localhost:8080/v1/clients
###
GET localhost:8080/v1/tools
###
GET localhost:8080/v1/blanks


###
POST localhost:8080/v1/user
Content-Type: application/json

{
  "email": "test@hehe.com",
  "password": "hehexd123123",
  "typeUser": {
    "idTypeUser": 2
  },
  "employee": {
    "name": "test",
    "surname": "test123"
  }
}
###
POST localhost:8080/v1/blank
Content-Type: application/json

{
  "codeGrade": 1,
  "idCoolantHole": 1,
  "name": "1/5 * 5 - Mill ",
  "stockQuantity": 100,
  "minimumQuantity": 100,
  "diameter": 2,
  "length": 5
}
###
POST localhost:8080/v1/client
Content-Type: application/json

{
  "name": "Bombardier",
  "phoneNumber": "8198199874"
}
###
POST localhost:8080/v1/tool
Content-Type: application/json

{
  "name": "Cordoba",
  "stockQuantity": "100",
  "minimumQuantity": "100"
}


###
PUT localhost:8080/v1/user
Content-Type: application/json

{
  "idUser": 6,
  "email": "test@hehe.ca",
  "password": "hehexd123123",
  "typeUser": {
    "idTypeUser": 2,
    "name": "test"
  }

}
###
PUT localhost:8080/v1/blank
Content-Type: application/json

{
  "idBlank": 3,
  "name": "1/5 * 5",
  "stockQuantity": 10,
  "minimumQuantity":10,
  "diameter": 20,
  "length": 50,
  "grade": {
    "code": 2,
    "name": "K01"
  },
  "coolantHole": {
    "idCoolantHole": 2,
    "quantity": 40,
    "diameter": 0,
    "TypeCoolantHole": {
      "idTypeCoolantHole": 1,
      "name": "Droit"
    }
  }
}

###
PUT localhost:8080/v1/client
Content-Type: application/json

{
  "idClient":5,
  "name":"AK47",
  "phoneNumber":"8778799887"
}
###
PUT localhost:8080/v1/tool
Content-Type: application/json

{
  "idTool":5,
  "minimumQuantity": "20"
}


###
DELETE  localhost:8080/v1/tool
Content-Type: application/json

{
  "idTool":6
}

