GET localhost:8080/v1/user/1/

###
GET localhost:8080/v1/users

###
POST localhost:8080/v1/user
Content-Type: application/json


{
  "idUserType": 1,
  "idEmployee": 1,
  "email": "test123@gmail.com",
  "password": "hehexd123"
}

###
PUT localhost:8080/v1/user
Content-Type: application/json


{
  "idUser": 1,
  "email": "test@hehe.com",
  "password": "hehexd123123",
  "typeUser": {
    "idTypeUser": 2
  },
  "employee": {
    "name": "test",
    "surname": "test123"
  }
}

###
POST localhost:8080/v1/client
Content-Type: application/json

{
  "name": "Test",
  "phoneNumber": "5146666666"
}

###
GET localhost:8080/v1/blank/2/

###