spring:
  datasource:
    username: root
    password:
    url: "jdbc:mariadb://localhost:3306"



mybatis:
  mapper-locations: classpath*:/mybatis/*
  configuration:
    map-underscore-to-camel-case: true
