spring:
  datasource:
    username: root
    password:
    url: "jdbc:mariadb://localhost:3306"
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"




mybatis:
  mapper-locations: classpath*:/mybatis/*
  configuration:
    map-underscore-to-camel-case: true
