spring:
#  datasource:
#    username: root
#    password: test123
#    url: "jdbc:mariadb://mariadb_database:3307"
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"




mybatis:
  mapper-locations: classpath*:/mybatis/*
  configuration:
    map-underscore-to-camel-case: true
